services:
  - type: web
    name: azuracast
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: PORT
        value: 10000
      - key: AZURACAST_HTTP_PORT
        value: 10000
      - key: WEB_PORT
        value: 10000
      - key: MARIADB_ROOT_PASSWORD
        value: azura_root_pass
      - key: INIT_REPO
        value: false
      - key: AZURACAST_DC_MODE
        value: true
      - key: AZURACAST_STANDALONE
        value: true
      - key: DB_IS_SQLITE
        value: true
      - key: SUPERVISOR_HTTP
        value: false
      - key: CACHE_DRIVER
        value: redis
      - key: SESSION_DRIVER
        value: redis
